'use client';
import {useMemo,useState} from 'react';import {ChevronRight} from 'lucide-react';
import {placementBands,placementCities,type Placements} from '@/lib/placements';import {integer,percent,titleCase} from '@/lib/format';import type {Candidate,City,Row} from '@/lib/tse';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
export function CityPlacements({cargo,placements,total,scope,cities,rows,candidate,onCity}:{cargo:string,placements:Placements,total:number,scope:string,cities:City[],rows:Row[],candidate:Candidate,onCity:(city:City)=>void}){
 const [selected,setSelected]=useState<{from:number,to:number,label:string}|'rest'|null>(null),[query,setQuery]=useState(''),[limit,setLimit]=useState(100);const bands=placementBands(cargo),included=placements.counts.slice(0,bands.at(-1)!.to).reduce((a,b)=>a+b,0);const groups=[...bands,{from:0,to:0,label:'Demais cidades'}];
 const list=useMemo(()=>{if(!selected)return [];const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return placementCities(cities,rows,selected==='rest'?null:selected,cargo).filter(x=>normalize(x.city.name).includes(normalize(query.trim())))},[cities,rows,selected,cargo,query]);
 return <><section aria-label="Posições do candidato nas cidades" className="mb-6"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h3 className="text-base font-semibold">Posição nas cidades</h3><span className="text-xs text-slate-400">{scope} · toque para ver as cidades</span></div><div className={`grid grid-cols-2 gap-3 sm:grid-cols-3 ${['1','3'].includes(cargo)?'xl:grid-cols-4':cargo==='5'?'xl:grid-cols-5':'xl:grid-cols-6'}`}>{groups.map(band=>{const count=band.from===0?total-included:placements.counts.slice(band.from-1,band.to).reduce((a,b)=>a+b,0),share=total?count/total*100:0;return <button key={band.from} onClick={()=>{setSelected(band.from===0?'rest':band);setQuery('');setLimit(100)}} className={`panel p-4 text-left transition hover:border-blue-400/40 focus-visible:outline-2 focus-visible:outline-blue-400 ${band.from===1?'border-blue-400/25 bg-blue-400/5':''}`} aria-label={`Ver cidades: ${band.label}`}><p className="flex items-center justify-between gap-2 text-xs text-slate-400">{band.label}<ChevronRight size={13}/></p><p className="mt-3 text-2xl font-semibold tabular-nums text-blue-200">{integer(count)}<span className="text-sm font-normal text-slate-500"> / {integer(total)}</span></p><p className="mt-2 text-xs text-slate-400">cidades · <strong className="font-medium text-blue-300">{percent(share)}</strong></p></button>})}</div><p className="mt-3 text-[11px] leading-5 text-slate-500">Grupos sem sobreposição · percentual de cidades da região. Posição por votos nominais válidos; empates compartilham posição. Cidades com zero votos ou sem resultado ficam em “Demais cidades”, com a posição indicada por —.{placements.loaded<total?` ${integer(total-placements.loaded)} cidades sem resultado válido disponível para o candidato.`:''}</p></section>
 <Sheet open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent className="w-full overflow-y-auto p-4 sm:max-w-2xl sm:p-6"><SheetHeader className="p-0 pr-7"><SheetTitle>{selected==='rest'?'Demais cidades':selected?.label} · {scope}</SheetTitle><SheetDescription>{titleCase(candidate.name)} · Nº {candidate.number} · percentual e posição no município. Toque na cidade para ver todos os candidatos.</SheetDescription></SheetHeader><label className="mt-2 text-xs text-slate-400">Buscar cidade<input aria-label="Buscar cidade no grupo" value={query} onChange={e=>{setQuery(e.target.value);setLimit(100)}} placeholder="Nome da cidade" className="mt-2 h-11 w-full rounded-lg border border-white/15 bg-slate-900 px-3 text-sm text-slate-200"/></label><p role="status" className="text-xs text-slate-400">{integer(list.length)} cidades{list.length>limit?` · mostrando ${integer(limit)}`:''}</p><div className="flex items-center justify-between gap-3 border-b border-white/10 pb-2 text-[10px] text-slate-500"><span className="flex-1">CIDADE</span><span className="w-16 text-right">VOTAÇÃO</span><span className="w-14 text-right">POSIÇÃO</span><span className="w-3"/></div><div className="divide-y divide-white/10">{list.slice(0,limit).map(item=><button key={item.city.uf+item.city.code} onClick={()=>{setSelected(null);onCity(item.city)}} className="flex w-full items-center gap-3 py-4 text-left hover:text-blue-200"><span className="min-w-0 flex-1 break-words text-sm leading-5">{titleCase(item.city.name)}<span className="mt-1 block text-xs text-slate-500">{item.city.uf.toUpperCase()}</span></span><span className="w-16 shrink-0 text-right text-xs tabular-nums">{item.result?percent(item.result.percentage):'Sem resultado'}{item.result?.votes===0&&<span className="mt-1 block text-[10px] text-slate-500">Sem votos</span>}</span><span className="w-14 shrink-0 text-right text-sm font-semibold tabular-nums text-blue-300">{item.position!==null?`${integer(item.position)}º`:'—'}</span><ChevronRight size={12} className="shrink-0 text-slate-500"/></button>)}</div>{!list.length&&<p className="py-6 text-center text-sm text-slate-400">Nenhuma cidade neste grupo ou nesta busca.</p>}{list.length>limit&&<button onClick={()=>setLimit(n=>n+100)} className="w-full rounded-lg border border-white/15 py-3 text-sm text-blue-200">Mostrar mais cidades ({integer(list.length-limit)} restantes)</button>}</SheetContent></Sheet></>;
}
