 'use client';
import {useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {Plus,Minus,RotateCcw,ArrowLeft,LoaderCircle} from 'lucide-react';
import {defaultViewport,boundViewport,zoomAt,pinchViewport,type Viewport,type Point} from '@/lib/map-viewport';
import {UFS} from '@/lib/tse';import {titleCase} from '@/lib/format';
import {changed,delta,mapColor,winner,labels,type Territory} from '@/lib/comparison';
const pp=(n:number|null)=>n===null?'Sem comparação':`${n>0?'+':''}${n.toLocaleString('pt-BR',{maximumFractionDigits:2})} p.p.`;
function project(p:number[]){return [p[0],-Math.log(Math.tan(Math.PI/4+p[1]*Math.PI/360))*180/Math.PI]}
export function ComparisonMap({uf,rows,states,onState,onSelect}:{uf:string,rows:Territory[],states:Territory[],onState:(uf:string)=>void,onSelect:(row:Territory)=>void}){
 const [geo,setGeo]=useState<any>(null),[error,setError]=useState(''),[hover,setHover]=useState<Territory|null>(null);
 useEffect(()=>{const a=new AbortController();setGeo(null);setError('');fetch(`/maps/${uf}.json`,{signal:a.signal}).then(r=>{if(!r.ok)throw new Error('Mapa indisponível.');return r.json()}).then(setGeo).catch(e=>{if(!a.signal.aborted)setError(e.message)});return()=>a.abort()},[uf]);
 const [viewport,setViewport]=useState<Viewport>(defaultViewport);const viewportRef=useRef(viewport);viewportRef.current=viewport;const pointers=useRef(new Map<number,Point>()),moved=useRef(false),gesture=useRef<{start:Viewport,point:Point,distance:number}|null>(null);
 useEffect(()=>{setViewport(defaultViewport);setHover(null);pointers.current.clear();gesture.current=null},[uf]);

 function point(e:ReactPointerEvent<SVGSVGElement>):Point{const r=e.currentTarget.getBoundingClientRect(),scale=Math.min(r.width/640,r.height/430);return {x:(e.clientX-r.left-(r.width-640*scale)/2)/scale,y:(e.clientY-r.top-(r.height-430*scale)/2)/scale}}
 function beginGesture(){const ps=[...pointers.current.values()];if(ps.length===2){const [a,b]=ps;gesture.current={start:viewportRef.current,point:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},distance:Math.hypot(a.x-b.x,a.y-b.y)};moved.current=true}else if(ps.length===1)gesture.current={start:viewportRef.current,point:ps[0],distance:0};else gesture.current=null;}
 function pointerDown(e:ReactPointerEvent<SVGSVGElement>){if(e.pointerType==='mouse'&&e.button!==0)return;if(!pointers.current.size)moved.current=false;pointers.current.set(e.pointerId,point(e));beginGesture();}
 function pointerMove(e:ReactPointerEvent<SVGSVGElement>){if(!pointers.current.has(e.pointerId)||!gesture.current)return;const p=point(e);pointers.current.set(e.pointerId,p);const ps=[...pointers.current.values()],g=gesture.current;if(ps.length===2){const [a,b]=ps,mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};setViewport(pinchViewport(g.start,g.point,mid,Math.hypot(a.x-b.x,a.y-b.y)/Math.max(g.distance,1)));moved.current=true;e.currentTarget.setPointerCapture(e.pointerId);setHover(null)}else if(ps.length===1&&g.start.zoom>1){const dx=p.x-g.point.x,dy=p.y-g.point.y;if(Math.hypot(dx,dy)>4||moved.current){moved.current=true;setViewport(boundViewport({...g.start,x:g.start.x+dx,y:g.start.y+dy}));e.currentTarget.setPointerCapture(e.pointerId);setHover(null)}}}
 function pointerUp(e:ReactPointerEvent<SVGSVGElement>){pointers.current.delete(e.pointerId);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);beginGesture();}

 const data=useMemo(()=>{
  if(!geo?.features)return [];
  const features:any[]=geo.features,rings=features.flatMap((f:any)=>f.geometry.type==='Polygon'?f.geometry.coordinates:f.geometry.coordinates.flat());
  const points=rings.flat().filter((p:number[])=>p[0]>-80&&p[0]<-30).map(project);
  const xs=points.map((p:number[])=>p[0]),ys=points.map((p:number[])=>p[1]);const minX=Math.min(...xs),minY=Math.min(...ys),width=Math.max(...xs)-minX,height=Math.max(...ys)-minY,scale=Math.min(590/width,390/height);
  const pt=(p:number[])=>{const [x,y]=project(p);return [(x-minX)*scale+(640-width*scale)/2,(y-minY)*scale+(430-height*scale)/2]};
  const cityMap=new Map(rows.map(r=>[r.ibge,r]));
  return features.map((f:any)=>{const id=String(f.properties.codarea),state=Object.keys(UFS).find(k=>UFS[k].id===id),row=uf==='br'?states.find(r=>r.uf===state):cityMap.get(id);const name=uf==='br'?(state?UFS[state].name:id):row?titleCase(row.name):`Município ${id}`;
   const polygons=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;
   const path=polygons.map((poly:any)=>poly.map((ring:any)=>ring.filter((p:number[])=>p[0]>-80&&p[0]<-30).map((p:number[],i:number)=>{const [x,y]=pt(p);return `${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')+'Z').join(' ')).join(' ');
   return {id,state,row:row?{...row,name}:null,path,name};
  });
 },[geo,rows,states,uf]);
 function select(d:typeof data[number]){if(moved.current)return;if(uf==='br'&&d.state)onState(d.state);else if(d.row)onSelect(d.row)}
 return <section className="panel overflow-hidden">
  <div className="flex items-center justify-between gap-3 border-b border-white/10 p-4"><div><p className="text-[10px] tracking-widest text-slate-400">LIDERANÇA E VARIAÇÃO · 1º TURNO</p><h3 className="mt-1 text-lg font-semibold">{uf==='br'?'Mapa dos estados':UFS[uf]?.name}</h3></div>{uf!=='br'&&<button onClick={()=>onState('br')} className="flex items-center gap-1 text-xs text-blue-200"><ArrowLeft size={15}/>Brasil</button>}</div>
  <div className="flex items-center justify-between px-4 py-2"><span className="text-xs text-slate-400">{Math.round(viewport.zoom*100)}% · arraste após ampliar</span><div className="flex gap-1"><button aria-label="Diminuir zoom da comparação" disabled={viewport.zoom<=1} onClick={()=>setViewport(v=>zoomAt(v,1/1.5))} className="flex size-11 items-center justify-center rounded-lg border border-white/10 sm:size-9 disabled:opacity-30"><Minus size={15}/></button><button aria-label="Ampliar mapa da comparação" disabled={viewport.zoom>=8} onClick={()=>setViewport(v=>zoomAt(v,1.5))} className="flex size-11 items-center justify-center rounded-lg border border-white/10 sm:size-9 disabled:opacity-30"><Plus size={15}/></button><button aria-label="Recentrar mapa da comparação" onClick={()=>setViewport(defaultViewport)} className="flex size-11 items-center justify-center rounded-lg border border-white/10 sm:size-9"><RotateCcw size={15}/></button></div></div>
  <div className="relative px-2">{error?<p role="alert" className="p-8 text-amber-200">{error}</p>:!geo?<div role="status" className="flex min-h-[280px] items-center justify-center gap-2 text-sm text-slate-400"><LoaderCircle className="animate-spin" size={18}/>Carregando mapa…</div>:<svg viewBox="0 0 640 430" className="max-h-[440px] w-full" style={{touchAction:viewport.zoom>1?'none':'pan-y',cursor:viewport.zoom>1?'grab':undefined}} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} aria-label={`Mapa comparativo de ${uf==='br'?'Brasil':UFS[uf]?.name}`}>
   <g transform={`translate(${viewport.x} ${viewport.y}) scale(${viewport.zoom})`}>{data.map(d=>{const w=winner(d.row?.after||null),description=`${d.name}: ${w&&w!=='tie'?labels[w]:'Empate ou sem dados'} · ${d.row&&w&&w!=='tie'?pp(delta(d.row,w)):'Sem comparação'}${d.row&&changed(d.row)?' · Troca de liderança':''}`;return <path key={d.id} d={d.path} fill={mapColor(d.row||undefined)} stroke={d.row&&changed(d.row)?'#2563eb':'#0b1421'} strokeWidth={d.row&&changed(d.row)?2:uf==='br'?1.5:.35} vectorEffect="non-scaling-stroke" role="button" tabIndex={d.row?0:-1} aria-label={description} onMouseEnter={()=>setHover(d.row)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(d.row)} onBlur={()=>setHover(null)} onClick={()=>select(d)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();moved.current=false;select(d)}}} className="cursor-pointer hover:brightness-125 focus:brightness-125"><title>{description}</title></path>})}</g>
  </svg>}{hover&&<div role="tooltip" className="pointer-events-none absolute bottom-2 left-3 right-3 rounded-lg border border-white/15 bg-slate-950/95 p-3 text-xs"><strong>{hover.name}</strong><span className="ml-2">{(()=>{const w=winner(hover.after);return w&&w!=='tie'?`${labels[w]} · ${pp(delta(hover,w))}`:'Empate ou sem comparação'})()}</span>{changed(hover)&&<span className="ml-2 text-blue-400">Troca de liderança</span>}</div>}</div>
  <div className="space-y-3 border-t border-white/10 p-4 text-xs text-slate-400"><p className="font-medium text-slate-200">Cor: mais votado em 2026 · tonalidade: delta do grupo</p>{[['Lula','hsl(0 68% 86%)','hsl(0 68% 60%)','hsl(0 68% 34%)'],["Bolsonaro's",'hsl(142 68% 86%)','hsl(142 68% 60%)','hsl(142 68% 34%)'],['Terceira via','hsl(275 68% 86%)','hsl(275 68% 60%)','hsl(275 68% 34%)']].map(([name,a,b,c])=><div key={name} className="grid grid-cols-[80px_minmax(0,1fr)] sm:grid-cols-[100px_minmax(0,1fr)] items-center gap-3"><span>{name}</span><div className="h-2.5 rounded" style={{background:`linear-gradient(to right,${a},${b},${c})`}}/></div>)}<div className="ml-[92px] sm:ml-[112px] flex justify-between text-[10px]"><span>≤ −20 p.p.</span><span>0</span><span>≥ +20 p.p.</span></div><p><span className="mr-2 inline-block size-2.5 border-2 border-blue-600"/>Troca de liderança · <span className="mx-1 inline-block size-2.5 bg-slate-600"/>Sem correspondência</p><p className="text-[11px] leading-5">Delta = percentual de 2026 − percentual de 2022, em pontos percentuais. Não é percentual de votos. {uf==='br'?'Toque num estado para abrir as cidades.':'Toque numa cidade para ver as duas votações.'}</p></div>
 </section>
}
