'use client';
import {useEffect,useMemo,useState} from 'react';
import {LoaderCircle,ArrowDownRight,ArrowUpRight,Search} from 'lucide-react';
import {ComparisonMap} from '@/components/comparison-map';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {UFS} from '@/lib/tse';import {integer,percent,titleCase} from '@/lib/format';
import {comparisonMetrics,transitionCities,labels,share,delta,winner,changed,correlation,report,type Transition,type Metric,type Territory,type ComparisonData} from '@/lib/comparison';
const pp=(n:number|null)=>n===null?'—':`${n>0?'+':''}${n.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})} p.p.`;
const pct=(n:number|null)=>n===null?'—':percent(n);
const groupName=(b:Metric,_year:2022|2026)=>labels[b];
const clean=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let saved:Promise<ComparisonData>|null=null;
function load(){if(!saved)saved=fetch('/data/comparison.json').then(r=>{if(!r.ok)throw new Error('Não foi possível abrir a comparação salva.');return r.json()}).catch(e=>{saved=null;throw e});return saved}
export function ElectionComparison({uf,onUf}:{uf:string,onUf:(uf:string)=>void}){
 const [data,setData]=useState<ComparisonData|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[metric,setMetric]=useState<Metric>('lula'),[reportScope,setReportScope]=useState('cities'),[pair,setPair]=useState<[Metric,Metric]>(['lula','lula']),[method,setMethod]=useState<'pearson'|'spearman'>('pearson'),[selected,setSelected]=useState<Territory|null>(null),[query,setQuery]=useState(''),[limit,setLimit]=useState(30),[onlyChanges,setOnlyChanges]=useState(false),[transition,setTransition]=useState<Transition|null>(null);
 useEffect(()=>{let active=true;setError('');load().then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[retry]);
 useEffect(()=>{setSelected(null);setQuery('');setLimit(30);setTransition(null);if(uf!=='br')setReportScope('cities')},[uf]);
 const cities=useMemo(()=>data?.cities.filter(c=>uf==='br'||c.uf===uf)||[],[data,uf]);
 const matched=useMemo(()=>cities.filter(c=>c.before&&c.after),[cities]);
 const points=useMemo(()=>matched.flatMap(row=>{const x=share(row.before,pair[0]),y=share(row.after,pair[1]);return x===null||y===null?[]:[{row,x,y}]}),[matched,pair]);
 const reports=useMemo(()=>report(reportScope==='states'?(data?.states||[]):cities,metric),[data,cities,metric,reportScope]);
 const swaps=useMemo(()=>({lulaToBolsonaro:transitionCities(cities,'lulaToBolsonaro'),bolsonaroToLula:transitionCities(cities,'bolsonaroToLula')}),[cities]);
 const visible=useMemo(()=>(transition?swaps[transition]:cities).filter(c=>(!onlyChanges||changed(c))&&clean(c.name+' '+c.uf).includes(clean(query))).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')),[cities,query,onlyChanges,transition,swaps]);
 const missing=cities.filter(c=>!c.before||!c.after);
 if(error)return <section role="alert" className="panel p-6 text-sm text-amber-200">{error}<button className="ml-3 underline" onClick={()=>setRetry(n=>n+1)}>Tentar novamente</button></section>;
 if(!data)return <section role="status" className="panel flex min-h-[260px] items-center justify-center gap-3 p-6 text-sm text-blue-200"><LoaderCircle className="animate-spin" size={24}/>Carregando comparação completa de 2022 e 2026…</section>;
 const summary=uf==='br'?data.national:data.states.find(s=>s.uf===uf)!;
 const scope=uf==='br'?'Brasil':UFS[uf]?.name;
 return <div className="space-y-6">
  <section className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] tracking-[.18em] text-blue-300">PRESIDÊNCIA · 1º TURNO</p><h2 className="mt-1 text-2xl font-semibold">2022 → 2026</h2><p className="mt-2 text-sm text-slate-400">Como mudou a votação em {scope}. Cada município tem o mesmo peso nas correlações.</p></div><span className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-400">{integer(matched.length)} cidades comparáveis</span></section>
  <section aria-label="Consolidado comparativo" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{comparisonMetrics.map(b=><div className="panel p-4" key={b}><p className={`text-sm font-medium ${b==='lula'?'text-red-300':b==='bolsonaro'?'text-green-300':b==='third'?'text-purple-300':'text-blue-300'}`}>{labels[b]}</p><div className="mt-3 flex items-baseline gap-3"><span className="text-sm text-slate-400">{pct(share(summary.before,b))}</span><span className="text-slate-600">→</span><strong className="text-2xl">{pct(share(summary.after,b))}</strong></div><p className="mt-2 text-sm tabular-nums">{pp(delta(summary,b))}</p><p className="mt-2 text-[10px] text-slate-500">2022 → 2026 · {b==='turnout'?'eleitorado apto':b==='nonValid'?'votos registrados':'votos válidos'} · {scope}</p></div>)}</section>
  <section aria-label="Trocas de liderança entre Lula e Bolsonaro's" className="grid gap-3 sm:grid-cols-2">{(['lulaToBolsonaro','bolsonaroToLula'] as Transition[]).map(direction=><button key={direction} aria-pressed={transition===direction} onClick={()=>{setTransition(current=>current===direction?null:direction);setQuery('');setOnlyChanges(false);setLimit(30);document.getElementById('comparison-city-list')?.scrollIntoView({behavior:'smooth',block:'start'})}} className={`panel p-5 text-left hover:border-blue-400/40 ${transition===direction?'border-blue-300/50':''}`}><p className={`text-sm font-medium ${direction==='lulaToBolsonaro'?'text-green-300':'text-red-300'}`}>{direction==='lulaToBolsonaro'?"Lula → Bolsonaro's":"Bolsonaro's → Lula"}</p><p className="mt-3 text-3xl font-semibold tabular-nums">{integer(swaps[direction].length)} <span className="text-sm font-normal text-slate-400">cidades</span></p><p className="mt-2 text-xs text-slate-400">Liderança em 2022 → liderança em 2026 · {scope} · toque para ver as cidades</p></button>)}</section>
  <p className="text-[11px] leading-5 text-slate-500">Bolsonaro's: Jair em 2022 e Flávio em 2026. Branco/Nulos soma brancos, nulos e demais votos não válidos, como % dos votos registrados. Comparecimento: % do eleitorado apto. Consolidado {uf==='br'?'nacional inclui o exterior':'da UF'}; percentuais pelos totais, sem média de municípios. Os contadores excluem empates e territórios sem correspondência.</p>
  <div className="grid items-start gap-5 xl:grid-cols-[1.12fr_1fr]">
   <ComparisonMap uf={uf} rows={cities} states={data.states} onState={onUf} onSelect={setSelected}/>
   <section className="panel p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] tracking-widest text-slate-400">ASSOCIAÇÃO ENTRE MUNICÍPIOS</p><h3 className="mt-1 text-lg font-semibold">Correlações entre grupos</h3></div><select aria-label="Método de correlação" value={method} onChange={e=>setMethod(e.target.value as typeof method)} className="rounded-lg border border-white/10 bg-[#0b1421] px-2 py-2 text-xs"><option value="pearson">Pearson</option><option value="spearman">Spearman</option></select></div>
    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[520px] table-fixed text-center text-xs"><caption className="mb-2 text-left text-[11px] text-slate-400">Linhas: 2022 · colunas: 2026 · toque para abrir o gráfico</caption><thead><tr><th className="w-[18%] p-2 text-left text-slate-500">2022 / 2026</th>{comparisonMetrics.map(b=><th className="p-2 font-medium" key={b}>{groupName(b,2026)}</th>)}</tr></thead><tbody>{comparisonMetrics.map(a=><tr key={a}><th className="p-2 text-left font-medium">{groupName(a,2022)}</th>{comparisonMetrics.map(b=>{const p=matched.flatMap(row=>{const x=share(row.before,a),y=share(row.after,b);return x===null||y===null?[]:[[x,y] as [number,number]]}),r=correlation(p,method),active=pair[0]===a&&pair[1]===b;return <td className="p-1" key={b}><button aria-label={`Correlação ${groupName(a,2022)} 2022 com ${groupName(b,2026)} 2026`} aria-pressed={active} onClick={()=>setPair([a,b])} className={`min-h-12 w-full rounded-lg border text-sm font-semibold tabular-nums ${active?'border-blue-300':'border-transparent'}`} style={{background:r===null?'#172533':`hsl(${r>=0?170:25} 45% ${18+Math.abs(r)*15}%)`}}>{r===null?'—':r.toLocaleString('pt-BR',{minimumFractionDigits:3,maximumFractionDigits:3})}</button></td>})}</tr>)}</tbody></table></div>
    <div className="mt-3 flex justify-between text-[10px] text-slate-400"><span>−1: relação inversa</span><span>0: sem associação</span><span>+1: relação direta</span></div>
    <p className="mt-4 text-xs leading-5 text-slate-400">{method==='pearson'?'Pearson compara os percentuais municipais.':'Spearman compara a ordem dos percentuais municipais, com empates em posição média.'} Uma correlação não identifica migração individual de eleitores. “—” indica menos de 3 cidades ou ausência de variação.</p>
    <Scatter points={points} pair={pair} onSelect={setSelected}/>
   </section>
  </div>
  <section className="panel p-4 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] tracking-widest text-slate-400">VARIAÇÃO EM PONTOS PERCENTUAIS</p><h3 className="mt-1 text-lg font-semibold">Onde mais ganhou e perdeu participação</h3></div><div className="flex w-full gap-2 sm:w-auto"><select aria-label="Indicador dos relatórios" value={metric} onChange={e=>setMetric(e.target.value as Metric)} className="min-w-0 flex-1 rounded-lg border border-white/10 bg-[#0b1421] p-2 text-sm">{comparisonMetrics.map(key=><option key={key} value={key}>{labels[key]}</option>)}</select><select aria-label="Território dos relatórios" value={reportScope} onChange={e=>setReportScope(e.target.value)} className="rounded-lg border border-white/10 bg-[#0b1421] p-2 text-sm"><option value="cities">Cidades</option><option value="states" disabled={uf!=='br'}>Estados</option></select></div></div>
   <div className="mt-5 grid gap-6 lg:grid-cols-2"><ReportList title="Maiores aumentos" entries={reports.gains} metric={metric} onSelect={setSelected} up/><ReportList title="Maiores quedas" entries={reports.losses} metric={metric} onSelect={setSelected}/></div>
   <p className="mt-4 text-[11px] leading-5 text-slate-500">Top 10 por delta, sem territórios ausentes. Branco/Nulos reúne todos os votos não válidos. Seu aumento representa maior participação desses votos, não melhor desempenho eleitoral.</p>
  </section>
  <section id="comparison-city-list" className="panel scroll-mt-4 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold">Explorar cidades</h3><p className="mt-1 text-xs text-slate-400">Percentual em cada eleição, delta e votação completa.</p></div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={onlyChanges} onChange={e=>{setOnlyChanges(e.target.checked);setLimit(30)}}/>Só trocas de liderança</label></div>{transition&&<div className="mt-3 flex items-center justify-between gap-3 rounded-lg border border-blue-400/20 p-3 text-xs"><span>{transition==='lulaToBolsonaro'?"Lula → Bolsonaro's":"Bolsonaro's → Lula"} · {integer(swaps[transition].length)} cidades</span><button onClick={()=>setTransition(null)} className="shrink-0 text-blue-200 underline">Ver todas</button></div>}<label className="mt-4 flex items-center gap-2 rounded-lg border border-white/10 bg-[#0b1421] p-3"><Search size={16} className="text-slate-500"/><input aria-label="Buscar cidade na comparação" placeholder="Buscar cidade…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(30)}} className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label>
   <div className="mt-3 divide-y divide-white/5">{visible.slice(0,limit).map(row=><button key={row.id} onClick={()=>setSelected(row)} className="flex w-full items-center justify-between gap-3 py-3 text-left hover:bg-white/5"><span className="min-w-0 break-words text-sm">{titleCase(row.name)} <span className="text-[10px] text-slate-500">{row.uf.toUpperCase()}</span>{changed(row)&&<span className="ml-2 text-[10px] text-yellow-300">troca</span>}</span><span className="shrink-0 text-right text-xs"><span className="text-slate-400">{pct(share(row.before,metric))} → {pct(share(row.after,metric))}</span><strong className="mt-1 block font-medium">{pp(delta(row,metric))}</strong></span></button>)}</div>{!visible.length&&<p className="py-6 text-center text-sm text-slate-500">Nenhuma cidade encontrada.</p>}{visible.length>limit&&<button onClick={()=>setLimit(n=>n+100)} className="mt-4 w-full rounded-lg border border-white/10 py-3 text-sm text-blue-200">Mostrar mais cidades · {integer(limit)} / {integer(visible.length)}</button>}
  </section>
  {missing.length>0&&<section className="panel p-4"><h3 className="text-sm font-semibold">Sem correspondência entre as eleições · {missing.length}</h3><p className="mt-2 text-xs leading-5 text-slate-400">Sem base nas duas eleições, o delta fica indisponível. Nenhum resultado foi preenchido com zero.</p>{missing.map(r=><button key={r.id} onClick={()=>setSelected(r)} className="mt-3 block text-left text-sm text-blue-200">{titleCase(r.name)} · {r.uf.toUpperCase()} · sem resultado de {r.before?'2026':'2022'}</button>)}</section>}
  <ComparisonDetails row={selected} data={data} onClose={()=>setSelected(null)}/>
 </div>
}
function ReportList({title,entries,metric,onSelect,up=false}:{title:string,entries:{row:Territory,value:number}[],metric:Metric,onSelect:(r:Territory)=>void,up?:boolean}){
 return <div><h4 className="mb-3 flex items-center gap-2 text-sm font-medium">{up?<ArrowUpRight size={17} className="text-blue-300"/>:<ArrowDownRight size={17} className="text-amber-300"/>}{title} · {labels[metric]}</h4><div className="divide-y divide-white/5">{entries.map(({row,value},i)=><button key={row.id} className="flex w-full items-center gap-3 py-3 text-left hover:bg-white/5" onClick={()=>onSelect({...row,name:row.code?row.name:UFS[row.uf]?.name||row.name})}><span className="w-5 shrink-0 text-[10px] text-slate-500">{i+1}</span><span className="min-w-0 flex-1 break-words text-sm">{row.code?titleCase(row.name):UFS[row.uf]?.name||row.name}<span className="ml-2 text-[10px] text-slate-500">{row.code?row.uf.toUpperCase():''}</span></span><span className="shrink-0 text-right"><strong className={`block text-sm tabular-nums ${up?'text-blue-200':'text-amber-200'}`}>{pp(value)}</strong><span className="text-[10px] text-slate-500">{pct(share(row.before,metric))} → {pct(share(row.after,metric))}</span></span></button>)}{!entries.length&&<p className="py-6 text-xs text-slate-500">Nenhum {up?'aumento':'recuo'} neste recorte.</p>}</div></div>
}
function Scatter({points,pair,onSelect}:{points:{row:Territory,x:number,y:number}[],pair:[Metric,Metric],onSelect:(r:Territory)=>void}){
 const [hover,setHover]=useState<typeof points[number]|null>(null);
 useEffect(()=>setHover(null),[points,pair]);
 return <div className="mt-6 border-t border-white/10 pt-4"><h4 className="text-sm font-medium">{groupName(pair[0],2022)} 2022 × {groupName(pair[1],2026)} 2026</h4><p className="mt-1 text-[11px] text-slate-500">{integer(points.length)} cidades · percentuais municipais · toque num ponto</p><div className="relative mt-3"><svg viewBox="0 0 500 345" className="w-full" role="img" aria-label={`Dispersão dos percentuais municipais de ${groupName(pair[0],2022)} em 2022 e ${groupName(pair[1],2026)} em 2026. Use a busca de cidades abaixo como alternativa.`}>{[0,25,50,75,100].map(n=><g key={n}><line x1={45} y1={290-n*2.5} x2={470} y2={290-n*2.5} stroke="#233044" strokeWidth=".5"/><line x1={45+n*4.25} y1="40" x2={45+n*4.25} y2="290" stroke="#233044" strokeWidth=".5"/><text x="35" y={294-n*2.5} textAnchor="end" fill="#94a3b8" fontSize="10">{n}</text><text x={45+n*4.25} y="307" textAnchor="middle" fill="#94a3b8" fontSize="10">{n}</text></g>)}<line x1="45" y1="290" x2="470" y2="40" stroke="#64748b" strokeDasharray="4 4" opacity=".5"/>{points.map(p=><circle key={p.row.id} cx={45+p.x*4.25} cy={290-p.y*2.5} r={hover?.row.id===p.row.id?5:2.3} fill={hover?.row.id===p.row.id?'#facc15':'#60a5fa'} opacity={hover?.row.id===p.row.id?1:.45} onMouseEnter={()=>setHover(p)} onMouseLeave={()=>setHover(null)} onClick={()=>onSelect(p.row)} className="cursor-pointer"><title>{titleCase(p.row.name)}: {pct(p.x)} → {pct(p.y)}</title></circle>)}<text x="255" y="334" textAnchor="middle" fill="#94a3b8" fontSize="11">{groupName(pair[0],2022)} · 2022 (%)</text><text transform="translate(12 168) rotate(-90)" textAnchor="middle" fill="#94a3b8" fontSize="11">{groupName(pair[1],2026)} · 2026 (%)</text></svg>{hover&&<div className="pointer-events-none absolute left-12 top-0 rounded border border-white/10 bg-slate-950/95 px-3 py-2 text-xs">{titleCase(hover.row.name)} · {pct(hover.x)} → {pct(hover.y)}</div>}</div></div>
}
function ComparisonDetails({row,data,onClose}:{row:Territory|null,data:ComparisonData,onClose:()=>void}){
 const [year,setYear]=useState<'2022'|'2026'>('2026');
 const totals=row?(year==='2022'?row.before:row.after):null;
 const votes=Object.entries(totals?.votes||{}).sort((a,b)=>b[1]-a[1]);
 const before=winner(row?.before||null),after=winner(row?.after||null);
 return <Sheet open={!!row} onOpenChange={open=>{if(!open)onClose()}}><SheetContent side="bottom" className="mx-auto max-h-[90dvh] max-w-3xl rounded-t-2xl border-white/10 bg-[#0b1421]">{row&&<><SheetHeader className="pr-10"><SheetTitle className="break-words">{titleCase(row.name)} · {row.uf.toUpperCase()}</SheetTitle><SheetDescription>Presidência · 1º turno · 2022 → 2026</SheetDescription></SheetHeader><div className="overflow-y-auto px-4 pb-6"><p className="mb-4 rounded-lg border border-white/10 p-3 text-xs">Liderança: {before&&before!=='tie'?groupName(before,2022):before==='tie'?'Empate':'Sem dados'} → {after&&after!=='tie'?groupName(after,2026):after==='tie'?'Empate':'Sem dados'}{changed(row)&&<strong className="ml-2 text-yellow-300">Troca de liderança</strong>}</p><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="text-slate-500"><th className="pb-2 font-normal">Grupo / indicador</th><th className="pb-2 text-right font-normal">2022</th><th className="pb-2 text-right font-normal">2026</th><th className="pb-2 text-right font-normal">Δ p.p.</th></tr></thead><tbody>{comparisonMetrics.map(key=><tr className="border-t border-white/5" key={key}><th className="py-3 pr-2 font-normal">{labels[key]}</th><td className="whitespace-nowrap py-3 text-right">{pct(share(row.before,key as Metric))}</td><td className="whitespace-nowrap py-3 text-right">{pct(share(row.after,key as Metric))}</td><td className="whitespace-nowrap py-3 text-right">{pp(delta(row,key as Metric))}</td></tr>)}</tbody></table></div><h4 className="mt-6 text-base font-semibold">Votação completa</h4><div className="my-3 flex gap-2">{(['2022','2026'] as const).map(y=><button key={y} aria-pressed={year===y} onClick={()=>setYear(y)} className={`rounded-lg border px-4 py-2 text-sm ${year===y?'border-blue-400/40 bg-blue-400/10 text-blue-200':'border-white/10'}`}>{y}</button>)}</div>{!totals?<p className="py-4 text-sm text-slate-400">Sem correspondência nesta eleição.</p>:<><div className="divide-y divide-white/5">{votes.map(([num,count],i)=><div className="flex items-center gap-3 py-3" key={num}><span className="w-4 text-[10px] text-slate-500">{i+1}</span><div className="min-w-0 flex-1"><p className="break-words text-sm">{titleCase(data.names[year][num]||`Candidato ${num}`)}</p><p className="mt-1 text-[10px] text-slate-500">Nº {num} · {integer(count)} votos</p></div><strong className="text-sm tabular-nums">{totals.valid?percent(count/totals.valid*100):'—'}</strong></div>)}</div><p className="mt-5 text-xs leading-6 text-slate-400">Eleitorado apto: {integer(totals.eligible)} · Comparecimento: {integer(totals.turnout)} · Abstenções: {integer(totals.abstention)}<br/>Branco/Nulos: {integer(totals.cast-totals.valid)} votos</p></>}</div></>}</SheetContent></Sheet>
}
