'use client';
import type {Candidate,Election,Row,Performance,City,Result} from './tse';
import type {AnalysisState} from './analysis-state';
import {blankAnalysis} from './analysis-state';
type ListedCandidate=Candidate&{pack:string};
export type Catalog={version:string,generatedAt:string,elections:Election[],scopes:Record<string,string>,performanceScopes:Record<string,string>,cityCounts:Record<string,Record<string,number>>};
const files=new Map<string,Promise<any>>();
async function json(path:string){let pending=files.get(path);if(!pending){pending=fetch(path,{cache:path==='/data/catalog.json'?'no-cache':'default'}).then(async r=>{if(!r.ok)throw new Error('Não foi possível abrir a base salva. Tente novamente.');return r.json()}).catch(e=>{files.delete(path);throw e});files.set(path,pending)}return pending;}
export function invalidateLocalData(){files.clear()}
export function catalog():Promise<Catalog>{return json('/data/catalog.json')}
export async function localCandidates(election:string,cargo:string,uf:string):Promise<ListedCandidate[]>{const meta=await catalog(),scope=`${election}:${cargo}:${cargo==='1'?'br':uf}`,file=meta.scopes[scope];if(!file)return [];const data=await json('/data/'+file+'?v='+encodeURIComponent(meta.version));return data.candidates.sort((a:Candidate,b:Candidate)=>a.name.localeCompare(b.name,'pt-BR'));}
export async function localAnalysis(candidate:Candidate,uf:string):Promise<AnalysisState>{const meta=await catalog(),list=await localCandidates(candidate.election,candidate.cargo,uf),listed=list.find(c=>c.id===candidate.id);if(!listed)throw new Error('Candidato ausente da base salva.');const [pack,cityFile,geometry,positions,ranks]=await Promise.all([json('/data/'+listed.pack+'?v='+encodeURIComponent(meta.version)),json('/data/cities.json?v='+encodeURIComponent(meta.version)),json('/maps/'+uf+'.json'),json(`/data/placements/${candidate.election}-${candidate.cargo}-${candidate.uf}.json?v=${encodeURIComponent(meta.version)}`),json('/data/'+listed.pack.replace(/^packs\//,'ranks/')+'?v='+encodeURIComponent(meta.version))]);if(ranks.version!==meta.version)throw new Error('Versões incompatíveis das posições por cidade.');if(positions.version!==meta.version)throw new Error('Versões incompatíveis das posições municipais.');const source=pack.candidates[candidate.id];if(!source)throw new Error('Resultados do candidato indisponíveis.');const candidateRanks=ranks.candidates[candidate.sqcand];if(!candidateRanks||candidateRanks.length!==source.rows.length)throw new Error('Posições municipais incompletas.');const key=candidate.id+':'+uf;const cityLookup=cityFile.cities[candidate.election];const rows:Row[]=source.rows.map((r:any[],i:number)=>({...cityLookup[r[0]],position:candidateRanks[i],votes:r[1],percentage:r[2],counted:r[3],updatedAt:r[4],status:source.candidate.status,destination:source.candidate.destination})).filter((r:Row)=>uf==='br'||r.uf===uf);const total=uf==='br'?Object.values(meta.cityCounts[candidate.election]).reduce((a,b)=>a+b,0):meta.cityCounts[candidate.election][uf]||0;const summary=candidate.cargo==='1'&&uf!=='br'?source.states.find((s:any)=>s.uf===uf)||null:source.summary;return {...blankAnalysis(key),candidate:source.candidate,rows,summary,geometry,placements:positions.candidates[candidate.sqcand]?.[uf]||{counts:Array(10).fill(0),loaded:0},cityCatalog:Object.values(cityLookup) as City[],states:uf==='br'?source.states:[],stateFailures:candidate.cargo==='1'&&uf==='br'?Math.max(0,27-source.states.length):0,processed:total,total,unavailable:Math.max(0,total-rows.length),complete:true,nextCursor:null};}
export async function localPerformances(election:string,cargo:string,uf:string):Promise<{rows:Performance[],processed:number,total:number,failed:number,unavailable:number}>{const meta=await catalog(),file=meta.performanceScopes[`${election}:${cargo}:${uf}`];if(!file)throw new Error('Cargo indisponível nesta região.');return json('/data/'+file+'?v='+encodeURIComponent(meta.version));}
export async function preloadLocal(election:string,cargo:string,uf:string){await Promise.all([localCandidates(election,cargo,uf),json('/maps/'+uf+'.json')])}

export type CandidateCityResult={candidate:Candidate,result:Result|null};
export async function localCityResults(election:string,cargo:string,city:City):Promise<CandidateCityResult[]>{
 const meta=await catalog(),list=await localCandidates(election,cargo,city.uf),index=await json('/data/city-index.json?v='+encodeURIComponent(meta.version));
 if(index.version!==meta.version)throw new Error('A base municipal está sendo atualizada. Recarregue a página.');
 const file=index.scopes[`${election}:${cargo}:${cargo==='1'?'br':city.uf}`]?.[city.uf+city.code];
 const batch=file?await json('/data/'+file+'?v='+encodeURIComponent(meta.version)):null;
 if(batch&&batch.version!==meta.version)throw new Error('Versões incompatíveis da base municipal.');
 const data=batch?.cities[city.uf+city.code],votes=new Map<string,any[]>((data?.rows||[]).map((r:any[])=>[r[0],r]));
 return list.map(candidate=>{const r=votes.get(candidate.sqcand);return {candidate,result:r?{votes:r[1],percentage:r[2],counted:data.counted,updatedAt:data.updatedAt,status:candidate.status,destination:candidate.destination}:null}}).sort((a,b)=>(b.result?.percentage??-1)-(a.result?.percentage??-1)||(b.result?.votes??-1)-(a.result?.votes??-1)||a.candidate.name.localeCompare(b.candidate.name,'pt-BR'));
}
