'use client';
import type {Candidate,Election,Row,Performance} from './tse';
import type {AnalysisState} from './analysis-state';
import {blankAnalysis} from './analysis-state';
type ListedCandidate=Candidate&{pack:string};
export type Catalog={version:string,generatedAt:string,elections:Election[],scopes:Record<string,string>,performanceScopes:Record<string,string>,cityCounts:Record<string,Record<string,number>>};
const files=new Map<string,Promise<any>>();
async function json(path:string){let pending=files.get(path);if(!pending){pending=fetch(path,{cache:path==='/data/catalog.json'?'no-cache':'default'}).then(async r=>{if(!r.ok)throw new Error('Não foi possível abrir a base salva. Tente novamente.');return r.json()}).catch(e=>{files.delete(path);throw e});files.set(path,pending)}return pending;}
export function invalidateLocalData(){files.clear()}
export function catalog():Promise<Catalog>{return json('/data/catalog.json')}
export async function localCandidates(election:string,cargo:string,uf:string):Promise<ListedCandidate[]>{const meta=await catalog(),scope=`${election}:${cargo}:${cargo==='1'?'br':uf}`,file=meta.scopes[scope];if(!file)return [];const data=await json('/data/'+file+'?v='+encodeURIComponent(meta.version));return data.candidates.sort((a:Candidate,b:Candidate)=>a.name.localeCompare(b.name,'pt-BR'));}
export async function localAnalysis(candidate:Candidate,uf:string):Promise<AnalysisState>{const meta=await catalog(),list=await localCandidates(candidate.election,candidate.cargo,uf),listed=list.find(c=>c.id===candidate.id);if(!listed)throw new Error('Candidato ausente da base salva.');const [pack,cityFile,geometry]=await Promise.all([json('/data/'+listed.pack+'?v='+encodeURIComponent(meta.version)),json('/data/cities.json?v='+encodeURIComponent(meta.version)),json('/maps/'+uf+'.json')]);const source=pack.candidates[candidate.id];if(!source)throw new Error('Resultados do candidato indisponíveis.');const key=candidate.id+':'+uf;const cityLookup=cityFile.cities[candidate.election];const rows:Row[]=source.rows.filter((r:any[])=>uf==='br'||r[0].startsWith(uf)).map((r:any[])=>({...cityLookup[r[0]],votes:r[1],percentage:r[2],counted:r[3],updatedAt:r[4],status:source.candidate.status,destination:source.candidate.destination}));const total=uf==='br'?Object.values(meta.cityCounts[candidate.election]).reduce((a,b)=>a+b,0):meta.cityCounts[candidate.election][uf]||0;const summary=candidate.cargo==='1'&&uf!=='br'?source.states.find((s:any)=>s.uf===uf)||null:source.summary;return {...blankAnalysis(key),candidate:source.candidate,rows,summary,geometry,states:uf==='br'?source.states:[],stateFailures:candidate.cargo==='1'&&uf==='br'?Math.max(0,27-source.states.length):0,processed:total,total,unavailable:Math.max(0,total-rows.length),complete:true,nextCursor:null};}
export async function localPerformances(election:string,cargo:string,uf:string):Promise<{rows:Performance[],processed:number,total:number,failed:number,unavailable:number}>{const meta=await catalog(),file=meta.performanceScopes[`${election}:${cargo}:${uf}`];if(!file)throw new Error('Cargo indisponível nesta região.');return json('/data/'+file+'?v='+encodeURIComponent(meta.version));}
export async function preloadLocal(election:string,cargo:string,uf:string){await Promise.all([localCandidates(election,cargo,uf),json('/maps/'+uf+'.json')])}
