import {env} from 'cloudflare:workers';
import {cachedRead,type CacheStore} from './collection';
import {parseElections,parseCities,parseCandidates,resultPath,UFS,type Election} from './tse';
const BASE='https://resultados.tse.jus.br/oficial/';
function bucket():R2Bucket{const b=(env as unknown as {TSE_CACHE?:R2Bucket}).TSE_CACHE;if(!b)throw new Error('Cache de dados indisponível. Tente novamente mais tarde.');return b;}
const store:CacheStore={async read(key){const o=await bucket().get('tse/'+key);return o?await o.json():null},async write(key,value){await bucket().put('tse/'+key,JSON.stringify(value),{httpMetadata:{contentType:'application/json'}})}};
async function readTse(path:string,refresh=false):Promise<any>{if(!/^[a-z0-9/\-.]+$/.test(path)||path.includes('..'))throw new Error('Caminho inválido.');const result=await cachedRead(store,path,async()=>{let response:Response|undefined;for(let attempt=0;attempt<2;attempt++){response=await fetch(BASE+path,{signal:AbortSignal.timeout(15000)});if(response.ok)break;if(response.status===404)return {__tseError:'Arquivo ainda não disponível no TSE.'};if(![502,503,504].includes(response.status)||attempt===1)throw new Error(response.status===404?'Arquivo ainda não disponível no TSE.':`TSE indisponível (${response.status}).`);}const json=await response!.json() as any;if(json.f&&json.f!=='o')throw new Error('Arquivo não oficial.');return {...json,cacheFetchedAt:Date.now()}},Date.now(),refresh,path.includes('/dados/')||path.includes('/config/mun-')?Infinity:900000);if(result.__tseError)throw new Error(result.__tseError);return result;}
const pending=new Map<string,Promise<any>>();
export async function tse(path:string,refresh=false):Promise<any>{const key=path+':'+refresh;const active=pending.get(key);if(active)return active;const request=readTse(path,refresh);pending.set(key,request);try{return await request}finally{pending.delete(key)}}
export async function elections():Promise<Election[]>{return parseElections(await tse('comum/config/ele-c.json'));}
export async function validate(election:string,cargo:string,uf:string){const e=(await elections()).find(x=>x.id===election&&x.cargos.some(c=>c.id===cargo));if(!e||cargo!=='1'&&!UFS[uf]||cargo==='8'&&uf!=='df'||cargo==='7'&&uf==='df')throw new Error('Eleição, cargo ou UF indisponível.');if(!(e.cargoAreas[cargo]||[]).includes('br')&&!(e.cargoAreas[cargo]||[]).includes(uf))throw new Error('UF não participa desta eleição.');return e;}
export async function cities(election:string){return parseCities(await tse(`ele2026/${election}/config/mun-e${election.padStart(6,'0')}-cm.json`));}
export async function candidates(election:string,cargo:string,uf:string,refresh=false){await validate(election,cargo,uf);const scope=cargo==='1'?'br':uf;return parseCandidates(await tse(resultPath(election,cargo,scope),refresh),{election,cargo,uf:scope});}
export async function geometry(uf:string):Promise<any>{if(uf==='br')throw new Error('Use o mapa nacional local.');if(!UFS[uf])throw new Error('UF inválida.');return cachedRead(store,'map-'+uf,async()=>{const r=await fetch(`https://servicodados.ibge.gov.br/api/v3/malhas/estados/${UFS[uf].id}?formato=application/vnd.geo+json&qualidade=minima&intrarregiao=municipio`,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('Mapa indisponível no IBGE.');return r.json()},Date.now(),false,Infinity);}
